### ISSUE TITLE
Latest version of the code

### ISSUE THREAD

**Issue by btastic** [wojo1086/satisfactory-sheet#1]
Hello,

are there any plans to check in the latest version of the code?

**Comment by wojo1086** [comment]
Hey,

It's already been updated to 1.0 of the game. Is there an issue you're facing with the site?

**Comment by btastic** [comment]
> Hey,
> 
> It's already been updated to 1.0 of the game. Is there an issue you're facing with the site?

I know, but this repo is not. Hence my question. Not an issue, but I'd like to try some improvements, to see whether I would get it going.

Edit: I didn't see the notes and 1.0 branches. I will try those :)

**Comment by wojo1086** [comment]
I updated master to reflect the 1.0 and notes branches.

**Comment by wojo1086** [comment]
What ideas did you have in mind? Would you like to work together on them?
